import datetime
from sqlalchemy import (
    Column,
    Integer,
    String,
    Text,
    ForeignKey,
    DateTime,
    Float,
    JSON,
)
from sqlalchemy.orm import relationship
from app.database import Base


class User(Base):
    __tablename__ = "users"

    id = Column(Integer, primary_key=True, index=True)
    username = Column(String, unique=True, index=True, nullable=False)
    email = Column(String, unique=True, index=True, nullable=False)
    hashed_password = Column(String, nullable=False)
    is_active = Column(Integer, default=1)  # 1 for True, 0 for False (SQLite compatibility)
    created_at = Column(DateTime, default=datetime.datetime.utcnow)


class APIDocument(Base):
    __tablename__ = "api_documents"

    id = Column(Integer, primary_key=True, index=True)
    url = Column(String, nullable=False, unique=True, index=True)
    title = Column(String, nullable=True)
    description = Column(Text, nullable=True)
    base_url = Column(String, nullable=True)
    api_type = Column(String, default="REST")  # REST, GraphQL, SOAP, Swagger, OpenAPI
    target_language = Column(String, nullable=True)
    
    # Ingestion tracking
    status = Column(String, default="pending")  # pending, crawling, chunking, analyzing, completed, failed
    error_log = Column(Text, nullable=True)
    
    # API scores generated by agents
    complexity_score = Column(Integer, default=0) # out of 100
    quality_score = Column(Integer, default=0) # out of 100
    security_score = Column(Integer, default=0) # out of 100
    
    created_at = Column(DateTime, default=datetime.datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.datetime.utcnow, onupdate=datetime.datetime.utcnow)

    # Relationships
    endpoints = relationship("Endpoint", back_populates="api_document", cascade="all, delete-orphan")
    auth_configs = relationship("AuthConfig", back_populates="api_document", cascade="all, delete-orphan")
    wrapper_tasks = relationship("WrapperTask", back_populates="api_document", cascade="all, delete-orphan")
    chat_messages = relationship("ChatMessage", back_populates="api_document", cascade="all, delete-orphan")


class AuthConfig(Base):
    __tablename__ = "auth_configs"

    id = Column(Integer, primary_key=True, index=True)
    api_doc_id = Column(Integer, ForeignKey("api_documents.id"), nullable=False)
    
    auth_type = Column(String, nullable=False)  # apiKey, oauth2, bearer, basic, none
    header_name = Column(String, nullable=True)  # Authorization, X-API-Key, etc.
    token_url = Column(String, nullable=True)
    description = Column(Text, nullable=True)
    
    # Rate Limits and suggestions
    rate_limit_limit = Column(Integer, nullable=True)
    rate_limit_window = Column(String, nullable=True)  # per minute, per hour
    rate_limit_strategy = Column(Text, nullable=True)

    # Relationships
    api_document = relationship("APIDocument", back_populates="auth_configs")


class Endpoint(Base):
    __tablename__ = "endpoints"

    id = Column(Integer, primary_key=True, index=True)
    api_doc_id = Column(Integer, ForeignKey("api_documents.id"), nullable=False)
    
    path = Column(String, nullable=False, index=True)
    method = Column(String, nullable=False)  # GET, POST, PUT, DELETE, PATCH
    summary = Column(String, nullable=True)
    description = Column(Text, nullable=True)
    
    parameters = Column(JSON, nullable=True)  # List of query/path params details
    request_schema = Column(JSON, nullable=True)  # Request body structure
    response_schema = Column(JSON, nullable=True)  # Successful response structure
    
    # Health checks
    last_checked = Column(DateTime, nullable=True)
    is_healthy = Column(String, default="unknown")  # healthy, unhealthy, unknown
    response_time_ms = Column(Integer, nullable=True)

    # Relationships
    api_document = relationship("APIDocument", back_populates="endpoints")


class WrapperTask(Base):
    __tablename__ = "wrapper_tasks"

    id = Column(Integer, primary_key=True, index=True)
    api_doc_id = Column(Integer, ForeignKey("api_documents.id"), nullable=False)
    
    language = Column(String, nullable=False)  # Python, TypeScript, Java, Go, Rust, etc.
    status = Column(String, default="pending")  # pending, generating, reviewing, completed, failed
    error_message = Column(Text, nullable=True)
    
    # Quality feedback from Review Agent
    quality_score = Column(Integer, default=0)
    security_score = Column(Integer, default=0)
    complexity_score = Column(Integer, default=0)
    
    # JSON containing structured generated code strings or file paths:
    # { "wrapper": "...", "readme": "...", "tests": "...", "zip_path": "..." }
    generated_files = Column(JSON, nullable=True)
    
    created_at = Column(DateTime, default=datetime.datetime.utcnow)

    # Relationships
    api_document = relationship("APIDocument", back_populates="wrapper_tasks")


class ChatMessage(Base):
    __tablename__ = "chat_messages"

    id = Column(Integer, primary_key=True, index=True)
    api_doc_id = Column(Integer, ForeignKey("api_documents.id"), nullable=False)
    
    role = Column(String, nullable=False)  # user, assistant
    content = Column(Text, nullable=False)
    created_at = Column(DateTime, default=datetime.datetime.utcnow)

    # Relationships
    api_document = relationship("APIDocument", back_populates="chat_messages")
